<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Version>1.1</Version>
    <Authors>Chase Redmon, Kuinox, Adam Sears</Authors>
    <Description>CatBox.NET is a .NET Library for uploading files, URLs, and modifying albums on CatBox.moe</Description>
    <PackageProjectUrl>https://github.com/ChaseDRedmon/CatBox.NET</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ChaseDRedmon/CatBox.NET</RepositoryUrl>
    <RepositoryType>Library</RepositoryType>
    <PackageTags>Catbox, Catbox.moe, Imgur, GfyCat</PackageTags>
    <Copyright>Copyright © 2025 Chase Redmon</Copyright>
    <PackageLicenseUrl>https://github.com/ChaseDRedmon/CatBox.NET/blob/main/license.txt</PackageLicenseUrl>
    <PackageReleaseNotes>Fix required description field on create album endpoint. Description is optional when creating an endpoint.</PackageReleaseNotes>
    <TargetFramework>net10.0</TargetFramework>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AnyOf" Version="0.5.0.1"/>
    <PackageReference Include="Intellenum" Version="2.0.1"/>
    <PackageReference Include="Microsoft.Extensions.Diagnostics" Version="10.0.0"/>
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0"/>
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.0.0"/>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0"/>
  </ItemGroup>
</Project>
