using System.Runtime.CompilerServices;
using CatBox.NET.Enums;
using CatBox.NET.Requests.Album;
using CatBox.NET.Requests.Album.Create;
using CatBox.NET.Requests.Album.Modify;
using CatBox.NET.Requests.File;
using CatBox.NET.Requests.URL;
using Microsoft.Extensions.Options;
using static CatBox.NET.Client.Common;

namespace CatBox.NET.Client;

public interface ICatBoxClient
{
    /// <summary>
    /// Enables uploading multiple files from disk (FileStream) to the API
    /// </summary>
    /// <param name="fileUploadRequest"></param>
    /// <param name="ct">Cancellation Token</param>
    /// <exception cref="ArgumentNullException">When <see cref="FileUploadRequest"/> is null</exception>
    /// <returns>Yield returns the CatBox filename of the uploaded image</returns>
    IAsyncEnumerable<string?> UploadFilesAsync(FileUploadRequest fileUploadRequest, CancellationToken ct = default);

    /// <summary>
    /// Enables uploading multiple files by URL to the API
    /// </summary>
    /// <param name="urlUploadRequest">Data to send to the API</param>
    /// <param name="ct">Cancellation Token</param>
    /// <exception cref="ArgumentNullException">When <see cref="UrlUploadRequest"/> is null</exception>
    /// <exception cref="HttpRequestException"> when something bad happens when talking to the API</exception>
    /// <returns>Yield returns the CatBox filename of the uploaded image</returns>
    IAsyncEnumerable<string?> UploadFilesAsUrlAsync(UrlUploadRequest urlUploadRequest, CancellationToken ct = default);

    /// <summary>
    /// Deletes multiple files by API file name
    /// </summary>
    /// <param name="deleteFileRequest">Files to delete from the server</param>
    /// <param name="ct">Cancellation Token</param>
    /// <exception cref="ArgumentNullException">When <see cref="DeleteFileRequest"/> is null</exception>
    /// <exception cref="ArgumentNullException">When <see cref="DeleteFileRequest.UserHash"/> is null</exception>
    /// <exception cref="ArgumentException">When <see cref="DeleteFileRequest.FileNames"/> is null, empty, or whitespace</exception>
    /// <exception cref="HttpRequestException"> when something bad happens when talking to the API</exception>
    /// <returns>Response string from the API</returns>
    Task<string?> DeleteMultipleFilesAsync(DeleteFileRequest deleteFileRequest, CancellationToken ct = default);

    /// <summary>
    /// Streams a single image to be uploaded
    /// </summary>
    /// <param name="fileUploadRequest"></param>
    /// <param name="ct">Cancellation Token</param>
    /// <exception cref="ArgumentNullException">When <see cref="StreamUploadRequest"/> is null</exception>
    /// <exception cref="ArgumentNullException">When <see cref="StreamUploadRequest.FileName"/> is null</exception>
    /// <exception cref="HttpRequestException"> when something bad happens when talking to the API</exception>
    /// <returns>Returns the CatBox filename of the uploaded image</returns>
    IAsyncEnumerable<string?> UploadFilesAsStreamAsync(IEnumerable<StreamUploadRequest> fileUploadRequest, CancellationToken ct = default);

    /// <summary>
    /// Creates an album on CatBox via provided file names generated by the API
    /// </summary>
    /// <param name="remoteCreateAlbumRequest">Data to pass to the API</param>
    /// <param name="ct">Cancellation Token</param>
    /// <exception cref="ArgumentNullException"> when <see cref="RemoteCreateAlbumRequest"/> is null</exception>
    /// <exception cref="ArgumentNullException"> when <see cref="RemoteCreateAlbumRequest.Description"/> is null, empty, or whitespace</exception>
    /// <exception cref="ArgumentNullException"> when <see cref="RemoteCreateAlbumRequest.Title"/> is null, empty, or whitespace</exception>
    /// <exception cref="ArgumentNullException"> when <see cref="RemoteCreateAlbumRequest.Files"/> is null, empty, or whitespace</exception>
    /// <exception cref="HttpRequestException"> when something bad happens when talking to the API</exception>
    /// <returns>Returns the created album URL</returns>
    Task<string?> CreateAlbumAsync(RemoteCreateAlbumRequest remoteCreateAlbumRequest, CancellationToken ct = default);

    /// <summary>
    /// Edits the content of album according to the content that is passed to the API
    /// </summary>
    /// <param name="editAlbumRequest">Data to pass to the API</param>
    /// <param name="ct">Cancellation Token</param>
    /// <exception cref="ArgumentNullException"> when <see cref="EditAlbumRequest"/> is null</exception>
    /// <exception cref="ArgumentNullException"> when <see cref="EditAlbumRequest.UserHash"/> is null, empty, or whitespace</exception>
    /// <exception cref="ArgumentNullException"> when <see cref="EditAlbumRequest.Description"/> is null, empty, or whitespace</exception>
    /// <exception cref="ArgumentNullException"> when <see cref="EditAlbumRequest.Title"/> is null, empty, or whitespace</exception>
    /// <exception cref="ArgumentNullException"> when <see cref="EditAlbumRequest.AlbumId"/> is null, empty, or whitespace</exception>
    /// <exception cref="ArgumentNullException"> when <see cref="EditAlbumRequest.Files"/> is null, empty, or whitespace</exception>
    /// <exception cref="HttpRequestException"> when something bad happens when talking to the API</exception>
    /// <returns>Response string from the API</returns>
    Task<string?> EditAlbumAsync(EditAlbumRequest editAlbumRequest, CancellationToken ct = default);

    /// <summary>
    /// This endpoint is for adding files to an album, removing files from an album, or deleting the album
    /// </summary>
    /// <param name="modifyAlbumImagesRequest">Data to pass to the API</param>
    /// <param name="ct">Cancellation Token</param>
    /// <exception cref="ArgumentNullException"> when <see cref="ModifyAlbumImagesRequest"/> is null </exception>
    /// <exception cref="ArgumentNullException"> when <see cref="ModifyAlbumImagesRequest.UserHash"/> is null, empty, or whitespace</exception>
    /// <exception cref="ArgumentNullException"> when <see cref="ModifyAlbumImagesRequest.Files"/> is null, empty, or whitespace</exception>
    /// <exception cref="ArgumentException"> when <see cref="ModifyAlbumImagesRequest.Request"/> is not valid for this requestBase type</exception>
    /// <exception cref="InvalidOperationException"> when <see cref="ModifyAlbumImagesRequest.Request"/> is not
    /// <see cref="CatBox.NET.Enums.RequestType.AddToAlbum"/>,
    /// <see cref="CatBox.NET.Enums.RequestType.RemoveFromAlbum"/>,
    /// or <see cref="CatBox.NET.Enums.RequestType.DeleteAlbum"/>
    /// </exception>
    /// <exception cref="HttpRequestException"> when something bad happens when talking to the API</exception>
    /// <returns>Response string from the API</returns>
    /// <remarks>
    /// The ModifyAlbumAsync method only supports the following requestBase types / verbs: <br/>
    /// <see cref="CatBox.NET.Enums.RequestType.AddToAlbum"/> <br/>
    /// <see cref="CatBox.NET.Enums.RequestType.RemoveFromAlbum"/> <br/>
    /// <see cref="CatBox.NET.Enums.RequestType.DeleteAlbum"/> . <br/> <br/>
    /// Use <see cref="ICatBoxClient.EditAlbumAsync"/> to edit an album</remarks>
    Task<string?> ModifyAlbumAsync(ModifyAlbumImagesRequest modifyAlbumImagesRequest, CancellationToken ct = default);
}

public sealed class CatBoxClient : ICatBoxClient
{
    private const long MaxFileSize = 209_715_200L; // 200MB in bytes

    private readonly HttpClient _client;
    private readonly CatboxOptions _catboxOptions;

    /// <summary>
    /// Creates a new <see cref="CatBoxClient"/>
    /// </summary>
    /// <param name="client"><see cref="HttpClient"/></param>
    /// <param name="catboxOptions"><see cref="IOptions{TOptions}"/></param>
    /// <exception cref="ArgumentNullException"><see cref="HttpClient"/> cannot be null</exception>
    /// <exception cref="ArgumentNullException"><see cref="CatboxOptions.CatBoxUrl"/> cannot be null</exception>
    /// <remarks>"CatBox API URL cannot be null. Check that URL was set by calling: <br/><code>.AddCatBoxServices(f => f.CatBoxUrl = new Uri("https://catbox.moe/user/api.php"));</code></remarks>
    public CatBoxClient(HttpClient client, IOptions<CatboxOptions> catboxOptions)
    {
        ArgumentNullException.ThrowIfNull(client);
        ArgumentNullException.ThrowIfNull(catboxOptions?.Value?.CatBoxUrl);
        
        _client = client;
        _catboxOptions = catboxOptions!.Value!;
    }

    /// <inheritdoc/>
    public async IAsyncEnumerable<string?> UploadFilesAsync(FileUploadRequest fileUploadRequest, [EnumeratorCancellation] CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(fileUploadRequest);

        foreach (var imageFile in fileUploadRequest.Files.Where(IsFileExtensionValid))
        {
            ct.ThrowIfCancellationRequested();
            await using var fileStream = File.OpenRead(imageFile.FullName);

            Throw.IfCatBoxFileSizeExceeds(fileStream.Length, MaxFileSize);

            using var content = new MultipartFormDataContent
            {
                { new StringContent(RequestType.UploadFile.Value), RequestParameters.Request },
                { new StreamContent(fileStream), RequestParameters.FileToUpload, imageFile.Name }
            };

            if (!string.IsNullOrWhiteSpace(fileUploadRequest.UserHash))
                content.Add(new StringContent(fileUploadRequest.UserHash), RequestParameters.UserHash);

            using var response = await _client.PostAsync(_catboxOptions.CatBoxUrl, content, ct);
            yield return await response.Content.ReadAsStringAsync(ct);
        }
    }
    
    /// <inheritdoc/>
    public async IAsyncEnumerable<string?> UploadFilesAsStreamAsync(IEnumerable<StreamUploadRequest> fileUploadRequest, [EnumeratorCancellation] CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(fileUploadRequest);

        foreach (var uploadRequest in fileUploadRequest)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(uploadRequest.FileName);

            if (uploadRequest.Stream.CanSeek)
                Throw.IfCatBoxFileSizeExceeds(uploadRequest.Stream.Length, MaxFileSize);

            using var content = new MultipartFormDataContent
            {
                { new StringContent(RequestType.UploadFile.Value), RequestParameters.Request },
                { new StreamContent(uploadRequest.Stream), RequestParameters.FileToUpload, uploadRequest.FileName }
            };

            if (!string.IsNullOrWhiteSpace(uploadRequest.UserHash))
                content.Add(new StringContent(uploadRequest.UserHash), RequestParameters.UserHash);

            using var response = await _client.PostAsync(_catboxOptions.CatBoxUrl, content, ct);
            yield return await response.Content.ReadAsStringAsync(ct);
        }
    }

    /// <inheritdoc/>
    public async IAsyncEnumerable<string?> UploadFilesAsUrlAsync(UrlUploadRequest urlUploadRequest, [EnumeratorCancellation] CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(urlUploadRequest);

        foreach (var fileUrl in urlUploadRequest.Files.Where(f => f is not null))
        {
            using var content = new MultipartFormDataContent // Disposing of MultipartFormDataContent, cascades disposal of String / Stream / Content classes
            {
                { new StringContent(RequestType.UrlUpload.Value), RequestParameters.Request },
                { new StringContent(fileUrl.AbsoluteUri), RequestParameters.Url }
            };

            if (!string.IsNullOrWhiteSpace(urlUploadRequest.UserHash))
                content.Add(new StringContent(urlUploadRequest.UserHash), RequestParameters.UserHash);

            using var response = await _client.PostAsync(_catboxOptions.CatBoxUrl, content, ct);
            yield return await response.Content.ReadAsStringAsync(ct);
        }
    }

    /// <inheritdoc/>
    public async Task<string?> DeleteMultipleFilesAsync(DeleteFileRequest deleteFileRequest, CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(deleteFileRequest);
        ArgumentException.ThrowIfNullOrWhiteSpace(deleteFileRequest.UserHash);

        var fileNames = string.Join(" ", deleteFileRequest.FileNames);
        ArgumentException.ThrowIfNullOrWhiteSpace(fileNames);

        using var content = new MultipartFormDataContent
        {
            { new StringContent(RequestType.DeleteFile.Value), RequestParameters.Request },
            { new StringContent(deleteFileRequest.UserHash), RequestParameters.UserHash },
            { new StringContent(fileNames), RequestParameters.Files }
        };

        using var response = await _client.PostAsync(_catboxOptions.CatBoxUrl, content, ct);
        return await response.Content.ReadAsStringAsync(ct);
    }
    
    /// <inheritdoc/>
    public async Task<string?> CreateAlbumAsync(RemoteCreateAlbumRequest remoteCreateAlbumRequest, CancellationToken ct = default)
    {
        ThrowIfAlbumCreationRequestIsInvalid(remoteCreateAlbumRequest);

        var links = remoteCreateAlbumRequest.Files.Select(link =>
        {
            if (link?.Contains(_catboxOptions.CatBoxUrl!.Host) is true)
            {
                return new Uri(link).PathAndQuery[1..];
            }

            return link;
        });

        var fileNames = string.Join(" ", links);
        ArgumentException.ThrowIfNullOrWhiteSpace(fileNames);

        using var content = new MultipartFormDataContent
        {
            { new StringContent(RequestType.CreateAlbum.Value), RequestParameters.Request },
            { new StringContent(remoteCreateAlbumRequest.Title), RequestParameters.Title },
            { new StringContent(fileNames), RequestParameters.Files }
        };

        if (!string.IsNullOrWhiteSpace(remoteCreateAlbumRequest.UserHash))
            content.Add(new StringContent(remoteCreateAlbumRequest.UserHash), RequestParameters.UserHash);

        if (!string.IsNullOrWhiteSpace(remoteCreateAlbumRequest.Description))
            content.Add(new StringContent(remoteCreateAlbumRequest.Description), RequestParameters.Description);

        using var response = await _client.PostAsync(_catboxOptions.CatBoxUrl, content, ct);
        return await response.Content.ReadAsStringAsync(ct);
    }

    /// <inheritdoc/>
#pragma warning disable CS0618 // API is not Obsolete, but should warn the user of dangerous functionality
    public async Task<string?> EditAlbumAsync(EditAlbumRequest editAlbumRequest, CancellationToken ct = default)
#pragma warning restore CS0618 // API is not Obsolete, but should warn the user of dangerous functionality
    {
        ArgumentNullException.ThrowIfNull(editAlbumRequest);
        ArgumentException.ThrowIfNullOrWhiteSpace(editAlbumRequest.UserHash);
        ArgumentException.ThrowIfNullOrWhiteSpace(editAlbumRequest.Description);
        ArgumentException.ThrowIfNullOrWhiteSpace(editAlbumRequest.Title);
        ArgumentException.ThrowIfNullOrWhiteSpace(editAlbumRequest.AlbumId);

        var fileNames = string.Join(" ", editAlbumRequest.Files);
        ArgumentException.ThrowIfNullOrWhiteSpace(fileNames);

        using var content = new MultipartFormDataContent
        {
            { new StringContent(RequestType.EditAlbum.Value), RequestParameters.Request },
            { new StringContent(editAlbumRequest.UserHash), RequestParameters.UserHash },
            { new StringContent(editAlbumRequest.AlbumId), RequestParameters.AlbumIdShort },
            { new StringContent(editAlbumRequest.Title), RequestParameters.Title },
            { new StringContent(editAlbumRequest.Description), RequestParameters.Description },
            { new StringContent(fileNames), RequestParameters.Files }
        };

        using var response = await _client.PostAsync(_catboxOptions.CatBoxUrl, content, ct);
        return await response.Content.ReadAsStringAsync(ct);
    }
    
    /// <inheritdoc/>
    public async Task<string?> ModifyAlbumAsync(ModifyAlbumImagesRequest modifyAlbumImagesRequest, CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(modifyAlbumImagesRequest);
        ArgumentException.ThrowIfNullOrWhiteSpace(modifyAlbumImagesRequest.UserHash);

        Throw.IfAlbumRequestTypeInvalid(IsAlbumRequestTypeValid(modifyAlbumImagesRequest), nameof(modifyAlbumImagesRequest.Request));
        Throw.IfAlbumOperationInvalid(modifyAlbumImagesRequest.Request, RequestType.AddToAlbum, RequestType.RemoveFromAlbum, RequestType.DeleteAlbum);

        var fileNames = string.Join(" ", modifyAlbumImagesRequest.Files);

        using var content = new MultipartFormDataContent
        {
            { new StringContent(modifyAlbumImagesRequest.Request.Value), RequestParameters.Request },
            { new StringContent(modifyAlbumImagesRequest.UserHash), RequestParameters.UserHash },
            { new StringContent(modifyAlbumImagesRequest.AlbumId), RequestParameters.AlbumIdShort }
        };

        if (modifyAlbumImagesRequest.Request == RequestType.AddToAlbum ||
            modifyAlbumImagesRequest.Request == RequestType.RemoveFromAlbum)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(fileNames);
            content.Add(new StringContent(fileNames), RequestParameters.Files);
        }

        using var response = await _client.PostAsync(_catboxOptions.CatBoxUrl, content, ct);
        return await response.Content.ReadAsStringAsync(ct);
    }
}