using CatBox.NET.Requests.CatBox;

namespace CatBox.NET.Client;

public interface ICatBoxClient
{
    /// <summary>
    /// Enables uploading multiple files from disk (FileStream) to the API
    /// </summary>
    /// <param name="fileUploadRequest"></param>
    /// <param name="ct">Cancellation Token</param>
    /// <exception cref="ArgumentNullException">When <see cref="FileUploadRequest"/> is null</exception>
    /// <returns>Yield returns the CatBox filename of the uploaded image</returns>
    IAsyncEnumerable<string?> UploadFiles(FileUploadRequest fileUploadRequest, CancellationToken ct = default);

    /// <summary>
    /// Enables uploading multiple files by URL to the API
    /// </summary>
    /// <param name="urlUploadRequest">Data to send to the API</param>
    /// <param name="ct">Cancellation Token</param>
    /// <exception cref="ArgumentNullException">When <see cref="UrlUploadRequest"/> is null</exception>
    /// <exception cref="HttpRequestException"> when something bad happens when talking to the API</exception>
    /// <returns>Yield returns the CatBox filename of the uploaded image</returns>
    IAsyncEnumerable<string?> UploadFilesAsUrl(UrlUploadRequest urlUploadRequest, CancellationToken ct = default);

    /// <summary>
    /// Deletes multiple files by API file name
    /// </summary>
    /// <param name="deleteFileRequest">Files to delete from the server</param>
    /// <param name="ct">Cancellation Token</param>
    /// <exception cref="ArgumentNullException">When <see cref="DeleteFileRequest"/> is null</exception>
    /// <exception cref="ArgumentNullException">When <see cref="DeleteFileRequest.UserHash"/> is null</exception>
    /// <exception cref="ArgumentException">When <see cref="DeleteFileRequest.FileNames"/> is null, empty, or whitespace</exception>
    /// <exception cref="HttpRequestException"> when something bad happens when talking to the API</exception>
    /// <returns>Response string from the API</returns>
    Task<string?> DeleteMultipleFiles(DeleteFileRequest deleteFileRequest, CancellationToken ct = default);

    /// <summary>
    /// Streams a single image to be uploaded
    /// </summary>
    /// <param name="fileUploadRequest"></param>
    /// <param name="ct">Cancellation Token</param>
    /// <exception cref="ArgumentNullException">When <see cref="StreamUploadRequest"/> is null</exception>
    /// <exception cref="ArgumentNullException">When <see cref="StreamUploadRequest.FileName"/> is null</exception>
    /// <exception cref="HttpRequestException"> when something bad happens when talking to the API</exception>
    /// <returns>Returns the CatBox filename of the uploaded image</returns>
    IAsyncEnumerable<string?> UploadFilesAsStream(IEnumerable<StreamUploadRequest> fileUploadRequest, CancellationToken ct = default);

    /// <summary>
    /// Creates an album on CatBox via provided file names generated by the API
    /// </summary>
    /// <param name="remoteCreateAlbumRequest">Data to pass to the API</param>
    /// <param name="ct">Cancellation Token</param>
    /// <exception cref="ArgumentNullException"> when <see cref="RemoteCreateAlbumRequest"/> is null</exception>
    /// <exception cref="ArgumentNullException"> when <see cref="RemoteCreateAlbumRequest.Description"/> is null, empty, or whitespace</exception>
    /// <exception cref="ArgumentNullException"> when <see cref="RemoteCreateAlbumRequest.Title"/> is null, empty, or whitespace</exception>
    /// <exception cref="ArgumentNullException"> when <see cref="RemoteCreateAlbumRequest.Files"/> is null, empty, or whitespace</exception>
    /// <exception cref="HttpRequestException"> when something bad happens when talking to the API</exception>
    /// <returns>Returns the created album URL</returns>
    Task<string?> CreateAlbum(RemoteCreateAlbumRequest remoteCreateAlbumRequest, CancellationToken ct = default);

    /// <summary>
    /// Edits the content of album according to the content that is passed to the API
    /// </summary>
    /// <param name="editAlbumRequest">Data to pass to the API</param>
    /// <param name="ct">Cancellation Token</param>
    /// <exception cref="ArgumentNullException"> when <see cref="EditAlbumRequest"/> is null</exception>
    /// <exception cref="ArgumentNullException"> when <see cref="EditAlbumRequest.UserHash"/> is null, empty, or whitespace</exception>
    /// <exception cref="ArgumentNullException"> when <see cref="EditAlbumRequest.Description"/> is null, empty, or whitespace</exception>
    /// <exception cref="ArgumentNullException"> when <see cref="EditAlbumRequest.Title"/> is null, empty, or whitespace</exception>
    /// <exception cref="ArgumentNullException"> when <see cref="EditAlbumRequest.AlbumId"/> is null, empty, or whitespace</exception>
    /// <exception cref="ArgumentNullException"> when <see cref="EditAlbumRequest.Files"/> is null, empty, or whitespace</exception>
    /// <exception cref="HttpRequestException"> when something bad happens when talking to the API</exception>
    /// <returns>Response string from the API</returns>
    Task<string?> EditAlbum(EditAlbumRequest editAlbumRequest, CancellationToken ct = default);

    /// <summary>
    /// This endpoint is for adding files to an album, removing files from an album, or deleting the album
    /// </summary>
    /// <param name="modifyAlbumImagesRequest">Data to pass to the API</param>
    /// <param name="ct">Cancellation Token</param>
    /// <exception cref="ArgumentNullException"> when <see cref="ModifyAlbumImagesRequest"/> is null </exception>
    /// <exception cref="ArgumentNullException"> when <see cref="ModifyAlbumImagesRequest.UserHash"/> is null, empty, or whitespace</exception>
    /// <exception cref="ArgumentNullException"> when <see cref="ModifyAlbumImagesRequest.Files"/> is null, empty, or whitespace</exception>
    /// <exception cref="ArgumentException"> when <see cref="ModifyAlbumImagesRequest.Request"/> is not valid for this request type</exception>
    /// <exception cref="InvalidOperationException"> when <see cref="ModifyAlbumImagesRequest.Request"/> is not
    /// <see cref="CatBox.NET.Enums.RequestType.AddToAlbum"/>,
    /// <see cref="CatBox.NET.Enums.RequestType.RemoveFromAlbum"/>,
    /// or <see cref="CatBox.NET.Enums.RequestType.DeleteAlbum"/> 
    /// </exception>
    /// <exception cref="HttpRequestException"> when something bad happens when talking to the API</exception>
    /// <returns>Response string from the API</returns>
    /// <remarks>
    /// The ModifyAlbum method only supports the following request types / verbs: <br/>
    /// <see cref="CatBox.NET.Enums.RequestType.AddToAlbum"/> <br/>
    /// <see cref="CatBox.NET.Enums.RequestType.RemoveFromAlbum"/> <br/>
    /// <see cref="CatBox.NET.Enums.RequestType.DeleteAlbum"/> . <br/> <br/>
    /// Use <see cref="ICatBoxClient.EditAlbum"/> to edit an album</remarks>
    Task<string?> ModifyAlbum(ModifyAlbumImagesRequest modifyAlbumImagesRequest, CancellationToken ct = default);
}
